app = "rmp-datasette"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[env]
  DATASETTE_SECRET = "your-secret-here"

[[mounts]]
  source = "data"
  destination = "/data"